### ISSUE TITLE
Catch FileNotFoundError in unschedule_command

### ISSUE THREAD

**Issue by tirtow** [tirtow/ally-bot#8]
```
Traceback (most recent call last):
  File "/home/tirtow/ally-bot/signup_handler.py", line 59, in handle
    await command.handle(message)
  File "/home/tirtow/ally-bot/command/unschedule_command.py", line 33, in handle
    os.remove(join("trial_info", message.channel.id + ".json"))
FileNotFoundError: [Errno 2] No such file or directory: 'trial_info/453230175044370452.json'
```

**Comment by tirtow** [comment]
Caused by user trying to unschedule trial that was added to dict but not completely created because an unhandled exception was raised.
